trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.5.0'

steps:
- task: UseTerraform@0
  inputs:
    terraformVersion: $(terraformVersion)

- script: |
    terraform init
  workingDirectory: 'infra'
  displayName: 'Terraform Init'

- script: |
    terraform plan -out=tfplan
  workingDirectory: 'infra'
  displayName: 'Terraform Plan'

- script: |
    terraform apply -auto-approve tfplan
  workingDirectory: 'infra'
  displayName: 'Terraform Apply'